### 1. Request a new JWT Token from Keycloak
# @name login
POST https://login.157.180.43.151.nip.io/realms/EduJournal/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=platform-backend&username=test&password=test&dummy=1

### 2. Hit Your Secured Backend Endpoint
GET http://localhost:8081/api/v1/secure-data
Authorization: Bearer {{login.response.body.access_token}}

### 3. Check Public Health Endpoint
GET http://localhost:8081/actuator/health