# ==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=8081

# ==========================================
# BUSINESS POSTGRESQL DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/business
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# KEYCLOAK OAUTH2 RESOURCE SERVER
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.157.180.43.151.nip.io/realms/EduJournal

# ==========================================
# MONGODB (LOCALIZATION & TRANSCRIPTS)
# ==========================================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=integrate_mongo
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${MONGO_USER:mongo_user}
spring.data.mongodb.password=${MONGO_PASSWORD:mongo_password}

# ==========================================
# REDIS (REDISSON L2 CACHE)
# ==========================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================================
# APACHE KAFKA
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=integrate-group


logging.level.org.springframework.security=TRACE

server.error.include-message=always
